version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: '@aws-sdk/client-lambda'
      - dependency-name: '@aws-sdk/client-s3'
      - dependency-name: '@aws-sdk/s3-request-presigner'
      - dependency-name: 'sharp'
      - dependency-name: 'autosize'
      - dependency-name: 'jackmoore/autosize'
      - dependency-name: 'github:jackmoore/autosize#6dea926b1ce18f01de1c62445d1ffc4a8bb80f6b'
      - dependency-name: '@types/autosize'
